@MinimalAPI_HostAddress = http://localhost:5056

GET {{MinimalAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MinimalAPI_HostAddress}}/todoItems
Content-Type: application/json

{
  "iscompleted":false
}
###
